# Generated by Django 3.0.5 on 2020-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='identifier',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
