# Generated by Django 3.0.5 on 2020-04-25 09:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20200423_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=3857),
        ),
    ]
