# Generated by Django 3.0.5 on 2020-04-25 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_auto_20200425_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=4326),
        ),
    ]
