# Generated by Django 3.0.5 on 2020-04-25 17:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20200425_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
