# Generated by Django 3.0.5 on 2020-04-25 17:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_river'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                srid=4326),
        ),
    ]
