# Generated by Django 3.0.5 on 2020-05-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0011_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
