# Generated by Django 3.0.5 on 2020-05-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_auto_20200502_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='poi_class',
            field=models.IntegerField(null=True),
        ),
    ]
