# Generated by Django 3.0.5 on 2020-05-06 19:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_mountainshadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainshadow',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
